### ISSUE TITLE
[BUG] Can't Delete Asset Profiles

### ISSUE THREAD

**Issue by cafigz** [ghostfolio/ghostfolio#6111]
**Bug Description**

Can't delete assets in Market data. It's grayed out as you can see in the screenshot.

<img width="155" height="159" alt="Image" src="https://github.com/user-attachments/assets/a0aaea86-ab56-44e2-a895-a77935a45732" />

**To Reproduce**

1. Go to Admin Control
2. Select Market Data
3. Press big blue + sign (Add Asset Profile)
4. Insert a Name, symbol or ISIN
5. Try to delete the created stock/ETF (See screenshots below~)

**Screenshots**

<img width="1442" height="209" alt="Image" src="https://github.com/user-attachments/assets/94e5aaa8-067f-4134-b480-a9b40cc0c99b" />

<img width="1407" height="204" alt="Image" src="https://github.com/user-attachments/assets/e51aa835-c638-4285-bb26-5a53eafc375b" />

**Expected Behavior**

Should be able to delete the Asset Profile. It's grayed out.

**Environment**

- Ghostfolio Version 2.224.2
- Self-hosted on Debian
- Browser Google Chrome

**Comment by dtslvr** [comment]
Thanks for the report, @cafigz.

This issue should already be fixed via https://github.com/ghostfolio/ghostfolio/pull/6090.

**Comment by cafigz** [comment]
> Thanks for the report, [@cafigz](https://github.com/cafigz).
> 
> This issue should already be fixed via [#6090](https://github.com/ghostfolio/ghostfolio/pull/6090).

Thanks for the quick reply. Do you recomend I change my self-hosted Ghostfolio so I can implement this change, or I should wait for the next update? When is the next update coming? Thanks in advance

**Comment by dtslvr** [comment]
A new release is expected within the next few days.

**Comment by cafigz** [comment]
> A new release is expected within the next few days.

As of today, still can't delete said Assets. The behaviour is the same as reported initially:

<img width="1431" height="200" alt="Image" src="https://github.com/user-attachments/assets/6c295927-12fe-4442-ba1b-bf901b4ef992" />
